apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: crawler-mind
  labels:
    app: mcp-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

