apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort   # ✅ 내부는 ClusterIP로 동작하지만 NodePort 고정해서 외부도 접근 가능
  ports:
    - port: {{ .Values.service.port }}       # Service 내부 포트 (5432)
      targetPort: {{ .Values.service.port }} # 컨테이너(Postgres) 포트 (5432)
      nodePort: 30542                        # ✅ 외부 노출 포트 고정
  selector:
    app: {{ .Release.Name }}

