replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5432

postgres:
  user: admin
  password: "YOUR_POSTGRES_PASSWORD"      # 문자열로 처리
  database: crawler_mind  # DATABASE_URL 기준

persistence:
  enabled: true
  size: 5Gi
  storageClass: standard   # ✅ 현재 클러스터 StorageClass 사용

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

