replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: Always

service:
  type: NodePort
  port: 5432

postgres:
  user: admin
  password: "YOUR_POSTGRES_PASSWORD"      # 문자열로 처리
  database: crawler_mind  # DATABASE_URL 기준

persistence:
  enabled: true
  size: 5Gi
  storageClass: standard   # ✅ 현재 클러스터 StorageClass 사용
  # PVC를 수동으로 관리하려면 existingClaim을 사용
  existingClaim: ""  # 기존 PVC 이름을 지정하면 새로 생성하지 않음

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

