{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      # mcp-client가 준비될 때까지 대기 (Kind 방식)
      initContainers:
        - name: wait-for-mcp-client
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - >
              until curl -f http://mcp-client:8000/health;
              do echo "⏳ waiting for mcp-client";
              sleep 5;
              done;

      containers:
        - name: frontend
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          # Kind 방식 Health Check
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          env:
            - name: NODE_ENV
              value: {{ .Values.frontend.env.NODE_ENV | quote }}
            - name: NEXT_PUBLIC_API_BASE_URL
              value: {{ .Values.frontend.env.NEXT_PUBLIC_API_BASE_URL | quote }}
            - name: API_BASE_URL
              value: "http://mcp-client:8000"
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"

          ports:
            - containerPort: 3000
              name: http
          
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
