{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crawler-mind.fullname" . }}-frontend
  labels:
    {{- include "crawler-mind.frontend.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  NODE_ENV: {{ .Values.frontend.env.NODE_ENV | quote }}
  API_BASE_URL: {{ .Values.frontend.env.API_BASE_URL | quote }}
  {{- $envConfig := index .Values.environments .Values.environment }}
  {{- if and $envConfig $envConfig.frontend $envConfig.frontend.env $envConfig.frontend.env.NEXT_PUBLIC_API_BASE_URL }}
  NEXT_PUBLIC_API_BASE_URL: {{ $envConfig.frontend.env.NEXT_PUBLIC_API_BASE_URL | quote }}
  {{- else if .Values.frontend.env.NEXT_PUBLIC_API_BASE_URL }}
  NEXT_PUBLIC_API_BASE_URL: {{ .Values.frontend.env.NEXT_PUBLIC_API_BASE_URL | quote }}
  {{- else if .Values.ingress.domain }}
  {{- if and .Values.ingress.tls.enabled }}
  NEXT_PUBLIC_API_BASE_URL: "https://{{ .Values.ingress.domain }}/api"
  {{- else }}
  NEXT_PUBLIC_API_BASE_URL: "http://{{ .Values.ingress.domain }}/api"
  {{- end }}
  {{- else }}
  NEXT_PUBLIC_API_BASE_URL: "/api"  # Use relative URL when no domain is set
  {{- end }}
{{- end }}
