{{- if .Values.mcpServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  labels:
    app: mcp-server
spec:
  type: {{ .Values.mcpServer.service.type }}
  ports:
    - port: {{ .Values.mcpServer.service.port }}
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    app: mcp-server
{{- end }}
