{{- if .Values.opensearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  type: {{ .Values.opensearch.service.type }}
  ports:
    - port: {{ .Values.opensearch.service.httpPort }}
      targetPort: {{ .Values.opensearch.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.opensearch.service.transportPort }}
      targetPort: {{ .Values.opensearch.service.transportPort }}
      protocol: TCP
      name: transport
  selector:
    app: opensearch
{{- end }}
