{{- if and .Values.opensearch.enabled .Values.opensearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.opensearch.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.opensearch.persistence.size }}
  storageClassName: {{ .Values.global.storageClass }}
{{- end }}
