{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  labels:
    {{- include "crawler-mind.qdrant.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.qdrant.replicaCount }}
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crawler-mind.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.qdrant.podSecurityContext | nindent 8 }}
      containers:
        - name: qdrant
          image: "{{ .Values.global.imageRegistry }}/dev/crawler/qdrant:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6333
              name: http
            - containerPort: 6334
              name: grpc
          volumeMounts:
            {{- if .Values.qdrant.persistence.enabled }}
            - name: qdrant-storage
              mountPath: /qdrant/storage
            {{- end }}
          resources:
            {{- toYaml .Values.qdrant.resources | nindent 12 }}
      volumes:
        {{- if .Values.qdrant.persistence.enabled }}
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc
        {{- else }}
        - name: qdrant-data
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
