replicaCount: 1

image:
  repository: qdrant/qdrant
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  httpPort: 6333
  grpcPort: 6334

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClassName: standard
  # PVC를 수동으로 관리하려면 existingClaim을 사용
  existingClaim: ""  # 기존 PVC 이름을 지정하면 새로 생성하지 않음

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: qdrant.alvinpark.xyz
      paths:
        - path: /
          pathType: Prefix
  tls: []
