apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-client
  namespace: crawler-mind
  labels:
    app: mcp-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mcp-client
  template:
    metadata:
      labels:
        app: mcp-client
    spec:
      # ✅ initContainer: postgres 준비될 때까지 대기
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command:
            - sh
            - -c
            - >
              until pg_isready -h postgres -p 5432 -U admin;
              do echo "⏳ waiting for postgres";
              sleep 2;
              done;

      containers:
        - name: mcp-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # ✅ readinessProbe: /health 체크
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # ✅ livenessProbe: /health 체크
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          env:
            - name: MCP_SERVER_URL
              value: {{ .Values.env.MCP_SERVER_URL | quote }}
            - name: CORS_ORIGINS
              value: {{ .Values.env.CORS_ORIGINS | quote }}
            - name: OPENAI_MODEL
              value: {{ .Values.env.OPENAI_MODEL | quote }}
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | quote }}

            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}

            - name: OPENSEARCH_HOST
              value: {{ .Values.env.OPENSEARCH_HOST | quote }}
            - name: OPENSEARCH_PORT
              value: {{ .Values.env.OPENSEARCH_PORT | quote }}

            - name: QDRANT_HOST
              value: {{ .Values.env.QDRANT_HOST | quote }}
            - name: QDRANT_PORT
              value: {{ .Values.env.QDRANT_PORT | quote }}

          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
