apiVersion: v1
kind: Service
metadata:
  name: mcp-client
  namespace: crawler-mind
  labels:
    app: mcp-client
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mcp-client
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

