{{- if .Values.mcpServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crawler-mind.fullname" . }}-mcp-server
  labels:
    {{- include "crawler-mind.mcpServer.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.mcpServer.autoscaling.enabled }}
  replicas: {{ .Values.mcpServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crawler-mind.mcpServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "crawler-mind.mcpServer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crawler-mind.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mcp-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "crawler-mind.image" (dict "Values" .Values "component" .Values.mcpServer.image.repository) }}
          imagePullPolicy: {{ .Values.mcpServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mcpServer.service.targetPort }}
              protocol: TCP
          env:
            - name: PYTHONUNBUFFERED
              value: {{ .Values.mcpServer.env.PYTHONUNBUFFERED | quote }}
          resources:
            {{- toYaml .Values.mcpServer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
