{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crawler-mind.fullname" . }}-postgresql
  labels:
    {{- include "crawler-mind.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
    {{- include "crawler-mind.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
