{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crawler-mind.fullname" . }}-postgresql
  labels:
    {{- include "crawler-mind.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
