{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "crawler-mind.fullname" . }}-qdrant
  labels:
    {{- include "crawler-mind.qdrant.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "crawler-mind.fullname" . }}-qdrant
  replicas: {{ .Values.qdrant.replicaCount }}
  selector:
    matchLabels:
      {{- include "crawler-mind.qdrant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "crawler-mind.qdrant.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crawler-mind.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: qdrant
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}"
          imagePullPolicy: {{ .Values.qdrant.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.qdrant.service.ports.http }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.qdrant.service.ports.grpc }}
              protocol: TCP
          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage
          {{- with .Values.qdrant.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qdrant.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.qdrant.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.qdrant.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: qdrant-data
        {{- with .Values.qdrant.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.qdrant.persistence.accessMode | quote }}
        {{- if .Values.qdrant.persistence.storageClass }}
        {{- if (eq "-" .Values.qdrant.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.qdrant.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.qdrant.persistence.size | quote }}
  {{- else }}
        volumes:
          - name: qdrant-data
            emptyDir: {}
  {{- end }}
{{- end }}
